通过urllib发送请求的时候，有可能会发送失败，可以通过try-except捕获异常，一般有HTTPError和URLError两种异常，其中HTTPError是URLError的子类
HTTP错误：针对浏览器无法连接到服务器而增加的报错，告诉浏览者该页面出了什么问题

正常情况下的获取网页内容：
import urllib.request
url='https://blog.csdn.net/hanhui22/article/details/109594359'
headers={
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69'
}
request=urllib.request.Request(url=url,headers=headers)
response=urllib.request.urlopen(request)
content=response.read().decode('utf-8')
print(content)
若此时url地址不对则会报错，于是可以用try-expect捕获该错误，改成：
import urllib.request
import urllib.error
url='https://blog.csd.net/hanhui22/article/details/109594359'
headers={
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69'
}
try:
    request=urllib.request.Request(url=url,headers=headers)
    response=urllib.request.urlopen(request)
    content=response.read().decode('utf-8')
    print(content)
except urllib.error.HTTPError:
    print("url地址错误")#指/109594359不对
except urllib.error.URLError:
    print("无该域名")#指https://blog.csdn.net/不对